name: CFitUK
favicon: null
layout_spectrum: 0.60487
typography_spectrum: 0.11424411041662097
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8765210621058941
  lightness: 0.517912472365424
  saturation: 0.9521684471983463
  rhythmicContrast: 0.6539156979415566
purpose: []
